"""Added transaction_type and virtual_card_id to transactions

Revision ID: 564c1dfd3722
Revises: 
Create Date: 2026-02-27 23:08:37.326932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564c1dfd3722'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('virtual_card_id', sa.Integer(), nullable=True))
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('virtual_card_id')
        batch_op.drop_column('transaction_type')

    # ### end Alembic commands ###
